sim('simulacion_validacion.slx',12);
angulo_simulacion=ans.simout.data+angulo_irl(end);
plot( ...
    tiempo_irl,angulo_irl, ...
    ans.simout.time,angulo_simulacion, ...
    tiempo_irl, exponencial_irl ...
    )